---
title: "Localización estaciones meteorológicas"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library('flexdashboard')
library('rgdal')
library("leaflet") 
library("sp")
library("sf")
library("raster")
library("dplyr")
library("here")
library("DT")
```


```{r readData, message=FALSE, warning=FALSE}
# Read spatial data 
estaciones <- sf::st_read(here::here('data/estaciones_clima.shp'), quiet = TRUE) 

est <- st_transform(estaciones, 4326)
```


```{r optionsMap}
popup_estaciones<- paste0("<strong>Nombre:</strong> ", est$DENOMINACI,
                   "<br><strong>Indicativo:</strong> ", est$INDICATIVO,
                   "<br><strong>Municipio:</strong> ", est$MUNICIPIO,
                    "<br><strong>Provincia:</strong> ", est$PROVINCIA,
                    "<br><strong>Elevación:</strong> ", est$ALTITUD,
                    "<br><strong>Fecha Inicio:</strong> ", est$FECHA_INIC,
                   "<br><strong>Fecha Fin:</strong> ", est$FECHA_FIN,
                   "<br><strong>Red:</strong> ", est$RED,
                    "<br><strong>Gestor:</strong> ", est$GESTOR)
```

Mapa
=============================================================================

```{r baseMap}
map_base <- leaflet() %>%
  addWMSTiles('http://www.ideandalucia.es/wms/mdt_2005?',
              layers = 'Sombreado_10',
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>', 
              group = 'Hillshade') %>% 
  addTiles(urlTemplate = "http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
           attribution = '<a href="https://carto.com/attributions">CARTO</a>',
           group = 'Basemap') %>%
  addWMSTiles('http://www.ideandalucia.es/services/toporaster10/wms?',
              layers = 'toporaster10',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'Topographical') %>%
  addWMSTiles('http://www.ideandalucia.es/wms/mta10r_2001-2013?',
              layers = 'mta10r_2001-2013',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'topo2013') %>% 
    addWMSTiles('http://www.ideandalucia.es/wms/mta10v_2007?',
              layers = 'mta10v_2007',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'topo2007') %>% 

  addProviderTiles("Esri.WorldImagery", group='Satellite') %>%
  # Layers control
  addLayersControl(position = 'bottomright',
                   baseGroups = c("Satellite", "Basemap","Hillshade","Topographical",  "topo2013", "topo2007"),
                   overlayGroups = c('Estaciones'),
                   options = layersControlOptions(collapsed = TRUE)) 





```

```{r}
map_base %>% addCircles(data = est, 
             group = 'Estaciones Climaticas',
             #lng=coordinates(es)[,'coords.x1'], 
             #lat=coordinates(dendro)[,'coords.x2'],
             fill=FALSE, color = 'blue', weight=3, 
             popup = popup_estaciones,
             label = ~INDICATIVO,
             labelOptions = labelOptions(noHide = FALSE,
                                         offset=c(0,-12), 
                                         textOnly = F,
                                         style = list("color" = "black")
                                         ))

```



Info
=============================================================================

Visualización de la distribución de las estaciones meteorológicas existentes en Andalucía, utilizando la información proporcionada por la REDIAM (Red de Información Ambiental de Andalucía). 

La última versión de los datos es de Abril de 2020, por tanto la información relativa a la fecha de fin de registros para cada una de las estaciones está desfasada.  






